---

# Fix for debian distribution
- name: Set Ansible distribution release
  set_fact:
    ansible_distribution_release: '{{ ansible_facts["distribution_major_version"].split("/")[0]
                                      if (ansible_facts["distribution_major_version"].split("/") | length) > 1
                                      else ansible_facts["distribution_release"] }}'

- name: Installing dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ca-certificates
      - apt-transport-https
      - software-properties-common

- name: Adding APT key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Adding APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: yes
