---

- import_tasks: install/ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: install/suse.yml
  when: ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'

- import_tasks: install/centos.yml
  when: ansible_distribution == 'CentOS'

- name: Installing packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-pip
      - "{{ docker_package }}"

- name: Installing Ansible PIP dependencies
  pip:
    name: "{{ item.name | default(item) }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ docker_pip_dependencies }}"
